### PR TITLE
Fixing problems with alt key and special characters like å, ä and ö

### PR DESCRIPTION
**Pull request by teemuteemu**
Should fix issues like #131

### CODE REVIEW

**Comment by marcbachmann** [comment]
Thanks. Looks good 👍

**Comment by rauchg** [comment]
This is the best thing that's happened to this project! Thank you!

**Comment by patrickhaug** [comment]
On german layout, ~ doesnt show up for alt/opt + n. i can hack it there while typing alt + shift + n and deleting the unicodes before the ~.

**Comment by marcbachmann** [comment]
> On german layout, ~ doesnt show up for alt/opt + n. i can hack it there while typing alt + shift + n and deleting the unicodes before the ~.

This terminal is so awesome, it makes you want to switch keyboards.

Umlauts are also still a problem. (ALT + u ... u)
Here's how iTerm handles them. I have no idea how hterm manages to swallow those inputs.
umlauts

**Pull request merged**
