### PR TITLE
Better default colors

### PR DESCRIPTION
**Pull request by dzannotti**
Provides better default colors for bash (more pastel), relates to https://github.com/zeit/hyperterm/issues/43

### CODE REVIEW

**Comment by rauchg** [comment]
So the overrides pref expects a list ? O.o

**Comment by rauchg** [comment]
Care to share a screenshot @dzannotti ? Thank you!

**Comment by dzannotti** [comment]
@rauchg sure thing here you go (keep in mind my .bash_prompt powerline additions that are not included in this PR) screen shot 2016-07-06 at 12 01 27

The reason it requires array form (or indexed object) is because it needs to overwrite the ascii palette (255 indexed colors), the source for this prefs is helpful to understand the context
https://github.com/dbkaplun/hterm-umdjs/blob/master/dist/index.js#L7867
https://github.com/dbkaplun/hterm-umdjs/blob/master/dist/index.js#L10815

I think a new settings page where each user could customize this colors, fontsize, font might be a better approach than forcing someone's defaults into everyone

**Comment by nfcampos** [comment]
@dzannotti that red (to my eyes at least) is difficult to see against the black background

**Comment by rauchg** [comment]
@hharnisc did a really great job. I like the new defaults! And config is coming

**Comment by rauchg** [comment]
Thanks @dzannotti

**Pull request closed without merging**
