### PR TITLE
Fix Close process 

### LINKED ISSUE #206: Closing terminal via Linux window controls leaves instances running
When I close by using the window controls in Linux, the window exits but Hyperterm plus the instances associated with electron remain running. Only quitting via the menu option "Quit" correctly terminates the instance.

### PR DESCRIPTION
**Pull request by c0b41**
#343 after more, close #206

maybe some #269 #123

### CODE REVIEW

**Comment by rauchg** [comment]
Maybe a comment is in order above it?

**Comment by rauchg** [comment]
also is `win.close` or `app.quit` what you want?

**Comment by rauchg** [comment]
Thanks btw!

**Comment by c0b41** [comment]
@rauchg yeah app.quit as well but win.close call window-all-closed event, I tried at the same time everything is fine

**Pull request merged**
