### PR TITLE
Add fallback monospace fonts for Menlo

### PR DESCRIPTION
**Pull request by OlliV**
These fonts should look similar to Menlo, especially DejaVu Sans Mono should be a decent fallback since Menlo seems to be based on it.

### CODE REVIEW

**Comment by rauchg** [comment]
We have to fix this for `hterm` now. It uses a specific preference in JS world. Alternatively, we could adapt the code to read the font from CSS (probably better)

**Comment by jhaynie** [comment]
i'm using zsh + iterm and the Powerline font.  when i manually change the font preference for the terminal i can get my zsh terminal to render fine.  would be nice to have a preference pane to allow custom font settings.

**Comment by OlliV** [comment]
@rauchg regardless of that, as long as there is any fonts in the css files I think we should have proper alternatives listed for different platforms, unless those are actually unused now.

**Comment by OlliV** [comment]
You are right, this patch doesn't fix the issue anymore :(

**Comment by leo** [comment]
IMHO, we should switch to [San Francisco Mono](http://daringfireball.net/linked/2016/04/20/san-fran-mono) on macOS + fallback for Windows, as soon as Apple publishes the font.

**Comment by OlliV** [comment]
Any idea what will be the license for it? I'm wondering if we could just bundle the font with the release package.

**Comment by leo** [comment]
@OlliV San Francisco Mono? You mean so that we can use it on windows as well? Because on macOS, we could just specify something like `font-family: -apple-system-mono`.

**Comment by OlliV** [comment]
@leo yes. If it's not possible then another option would be to possibly bundle some other font for other platforms. Otherwise we'd have to figure out what works for different linux distributions, Android, Windows etc.

**Comment by leo** [comment]
@OlliV Android? 😸

**Comment by OlliV** [comment]
@leo :D Well, I just mean that why wouldn't we make it platform independent if it's easily possible. Fonts are still something that's not always portable across platforms.

**Comment by rauchg** [comment]
Fixed. Thanks @OlliV

**Pull request closed without merging**
