### PR TITLE
Validate cursorColor value and apply default if it fails 

### PR DESCRIPTION
**Pull request by jwhitmarsh**
Originally was #562 but I did the work on master, so switched it to a branch. Apologies for the mess!

Fixes 527

### CODE REVIEW

**Comment by leo** [comment]
👌

**Comment by jwhitmarsh** [comment]
Was that rebase correct?

**Comment by MrRio** [comment]
@jwhitmarsh I'm getting "This branch is out-of-date with the base branch - Merge the latest changes from master into this branch."

**Comment by jwhitmarsh** [comment]
Sorry, it was showing up as 'Good to merge' for me - i've re-rebased it :)

**Comment by leo** [comment]
Thanks a lot! 😊

**Pull request merged**
