### PR TITLE
configurable cursor opacity

### PR DESCRIPTION
**Pull request by hharnisc**
Before
screen shot 2016-07-07 at 7 26 07 pm
After
screen shot 2016-07-07 at 8 09 02 pm

### CODE REVIEW

**Comment by rauchg** [comment]
I want this cfg flag! Will need a refactor.

**Comment by hharnisc** [comment]
Working on refactoring this now, expect it soon as long as I don't get interrupted

**Comment by hharnisc** [comment]
@rauchg could you give this another look? The refactor done here is beautiful by the way, very well done!

**Comment by huytd** [comment]
Will it be conflicted with the `cursorColor` if we put a `rgba` value in it?

**Comment by rauchg** [comment]
@huytd that actually sounds like a really good idea. @hharnisc do you think it's tractable to try to extra the alpha value from `cursorColor`?

**Comment by hharnisc** [comment]
@huytd @rauchg this seems like a good idea, since it removes the need to add another line in the [getStyleSheet](https://github.com/zeit/hyperterm/blob/master/app/lib/components/term.js#L93) function.

I'm thinking using the `color` module to parse out the cursor color (hex, rgb(a), hsl(a), ...) then set the alpha value to the `cursorOpacity` setting.

Here's a code sample:

https://tonicdev.com/578b9f2f9cdcc013002a89e6/578b9f2f9cdcc013002a89e7

In this scheme the cursorOpacity always overrides the cursorColor alpha value.

**Comment by hharnisc** [comment]
@rauchg updated the fork if you'd like to give it another go. 

This works and seems predictable, but I could see an argument for only having a cursor color that allows you to set alpha and not having a cursorOpacity as well. But I think that would need to be well documented.

I could also see an argument for allowing cursor opacity set to null or undefined to disable it. 

I think I'd lean toward this implementation (override cursor color) since I would expect more people would catch

```js
cursorColor: '#333',
cursorOpacity: 0.75
```

over 

```js
cursorColor: 'rgba(50, 50, 50, 0.75)',
```

**Comment by huytd** [comment]
Yeah. This is better. So we can have both `rgba` value in `cursorColor` and a separate `cursorOpacity` property, which will be higher priority and it can overrides the `cursorColor`.

This is a good way. I think we need to have this documented carefully :D 

👍 my vote up for this

**Comment by hharnisc** [comment]
Thank you for the feedback @huytd 😄

**Comment by filipelinhares** [comment]
Hi guys, I've seen some theme packages using this snippet of code:

```css
.cursor-node {
    mix-blend-mode: difference;
}
```

**Before**
image

**After**
image

**Comment by hharnisc** [comment]
@filipelinhares That's pretty cool! Wasn't familiar with that CSS rule. That seems more like another configuration flag to me though, since it's doing color blending rather than opacity.

**Comment by hhsnopek** [comment]
I don't think splitting the color and opacity is a great idea, considering that we have `rgba` for the specific reason of adding alpha. You could also use css4 `#[alpha][alpha][color][color][color][color][color][color]`, `#DDffffff` light opacity on white

**Comment by rauchg** [comment]
I would strongly prefer to have only *one* config (I don't want that file to be huge). What we can do is provide our default purple in the `rgba` format and clarify in the text that we support any css color format :)

Also, @filipelinhares you just blew my mind. I didn't know that existed.

Thanks @hharnisc and everyone else for pitching in!

**Comment by hharnisc** [comment]
Glad we're getting down the bottom of this! This implementation feels pretty good and the configuration seems really straight forward. Nice work everyone!

@rauchg ready to go when you are 😄

**Comment by rauchg** [comment]
Sooooooo awesome

**Pull request merged**
