### PR TITLE
Allow for specifying global hotkey for toggling visibility

### PR DESCRIPTION
**Pull request by sheerun**
I've implemented it as a default plugin for hyperterm. My presented suggestion is to put default hyperterm plugins into `@hyperterm` folder and namespace modules with `@hyperterm` scope. You might consider claiming this scope on npm.

As for hotkey behavior, it is the same as in iTerm2:

- If any window is hidden, show all
- If all windows are shown, hide all
- Preserve focused window and z-order when showing / hidding them.

The hotkey is configurable with "hotkey" option.

### CODE REVIEW

**Comment by sheerun** [comment]
One annoying thing that will be hard to fix: when hidding iTerm2 with lgobal hotkey, previously focused app (e.g. chrome) gets refocused. This implementation just hides Hyperterm without re-focusing.

This can be fixed later, I think

**Comment by rauchg** [comment]
I'd love this to be shipped separately. @italoacasas is working also on a new plugin listing page where we can highlight our recommendations such as this one, `hypercwd` etc.

image

**Comment by soutar** [comment]
@rauchg @sheerun I published a package to do this today after installing HyperTerm and missing iTerm's hotkey feature. I'd love feedback from you two if you have time.

https://github.com/soutar/hyperterm-summon

**Comment by sheerun** [comment]
@soutar Works wonderfully, thanks. I'd prefer "hotkey" configuration option, but otherwise ok.

**Comment by rauchg** [comment]
@soutar amazing

**Comment by soutar** [comment]
@rauchg @sheerun Cheers for having a look both of you. Regarding hotkey/shortcut config options, I'm not particularly tied to the naming so if you want to PR the change I'll happily merge.

**Pull request closed without merging**
