### PR TITLE
Comply XO's "jsx-filename-extension" rule

### PR DESCRIPTION
**Pull request by davegomez**

### CODE REVIEW

**Comment by davegomez** [comment]
Any comment @ekmartin?

**Comment by ekmartin** [comment]
Yes, sorry - here it is: I'm not sure if I agree with this. Dan Abramov explains it much better than I do though: https://github.com/airbnb/javascript/pull/985#issuecomment-239145468

**Comment by davegomez** [comment]
I agree with that too but we are trying to comply with XO's rules #730, is not about what we think or what we like.

**Comment by ekmartin** [comment]
Of course it is - for such a large project as this there's really not that much virtue in trying to comply with rules that we don't agree with, at least in my opinion. If the rule makes sense, definitely, but if not I don't see the huge win in bending the project in a way that feels unnatural.

I don't think a lot of people will go into developing HyperTerm with an expectation of how everything should look based on them knowing about `xo`. They'll run the linter, and fix what's being complained about - regardless of whether they agree with it or not. Thus I think some bikeshedding on issues like this is warranted, and not something to be afraid of.

**Comment by ekmartin** [comment]
We shouldn't disable the rule nonetheless though, if we don't want `.jsx` we should set it to `react/jsx-filename-extension: ["error", { "extensions": [".js"] }]`

**Comment by davegomez** [comment]
I don't fight with linters and I don't see any problem in renaming the files, but I agree that use the rule `react/jsx-filename-extension: ["error", { "extensions": [".js"] }]` could be a solution, but I don't see any gain either way.

**Comment by matheuss** [comment]
This rule was [removed](https://github.com/sindresorhus/eslint-config-xo-react/commit/00853d45598a892e487e61d561b1adb65ec55508) from `eslint-config-xo-react` 😅

**Comment by davegomez** [comment]
@matheuss awesome, we should update ruleset then

**Comment by matheuss** [comment]
cc @sindresorhus

**Comment by ekmartin** [comment]
Closing in favor of #741.

**Comment by sindresorhus** [comment]
I already commented about it here: https://github.com/zeit/hyperterm/pull/723#discussion_r79976176

**Pull request closed without merging**
