### PR TITLE
Use configured shell to update plugins

### PR DESCRIPTION
**Pull request by albinekb**
Request to do so in #440 
However, this requires the user to have `npm` installed (#381) ...
Based on https://github.com/sindresorhus/shell-env/pull/3

### CODE REVIEW

**Comment by albinekb** [comment]
@mike-engel Could you test if this works for your setup? 👼

**Comment by mike-engel** [comment]
Just tested again. Nice work! 👍

**Comment by albinekb** [comment]
@rauchg have a look 👼

**Comment by leo** [comment]
We should wait until https://github.com/sindresorhus/shell-env/pull/3 was merged. Because loading something directly from a GitHub branch is way too risky!

**Comment by sindresorhus** [comment]
shell-env@0.2.0 with ability to specify shell is out.

**Comment by albinekb** [comment]
Thanks @sindresorhus ❤️

**Comment by albinekb** [comment]
Pingeling @leo @rauchg have a look 🦄

**Comment by leo** [comment]
Thank you all for your patience and the changes made! 😘

**Pull request merged**
