### PR TITLE
Example React Native implementation of hyperterm header

### PR DESCRIPTION
**Pull request by necolas**
Hey,

Here's a rough example of how you could use React Native to build the terminal's header. There are a few warnings in the console about style properties React Native doesn't currently know about.

You'll notice that CSS pseudo-classes (e.g. `:hover`) aren't supported. However, it's quite common to track state like hover in JavaScript anyway (as you do in `Tab`).

Something else worth mentioning is that `View` is the main building block and has a column-based flexbox layout by default. It won't accept any text or font styles; those have to be applied to a `Text` element. A helpful pattern is to create a component that encapsulates the typography concerns, e.g., `<AppText color='white' size='normal'>bash</AppText>`.

User theming could be done with JS objects. Since you'd be working with objects and not strings, you can better control exactly what custom styles you apply to the components. For example, the color but not position of text nodes could be customizable:

```
exports.decorateConfig = (config) => {
  return Object.assign({}, config, {
    borderColor: 'yellow',
    cursorColor: 'yellow',
    css: Object.assign({}, config.css, {
      tabText: {
        color: 'yellow', // this style is a valid override
        position: 'fixed' // this style is not, and you ignore it
      },
      tabsTitle: {
        color: 'yellow'
      }
    })
  });
}
```

### CODE REVIEW

**Comment by dimorphic** [comment]
Nice initiative, but unfortunately you won't be able to spawn [child processes](https://nodejs.org/api/child_process.html#child_process_child_process) (pseudo terminal our case) on mobile devices and have this beauty of a terminal. Building the app via React Native or any other hybrid way won't work (for now).

Electron has Node.js and Chromium under the hood, that's where the Ju Ju magic comes from. :)

:+1:

**Comment by dimorphic** [comment]
I was wrong, there is hope! https://github.com/jxcore/jxcore-cordova

Unfortunately seems they halted active development, but hey open source! <3 - [blog post](http://www.nubisa.com/nubisa-halting-active-development-on-jxcore-platform/)

**Comment by necolas** [comment]
Huh?

**Comment by necolas** [comment]
Chatted with @rauchg. Closing this example; will leave to him to port the existing code if interested.

**Pull request closed without merging**
