### PR TITLE
Support config for default width/height of browser window

### PR DESCRIPTION
**Pull request by tamagokun**
This addresses #108 (sort of). Ideally I think rows/cols make more sense since this is a terminal application. This at least gives the user something to work with.

### CODE REVIEW

**Comment by rauchg** [comment]
I like the idea of just memorizing the last size the window was open. What do you think?

**Comment by tamagokun** [comment]
For anyone that creates more than one window for one-off commands or having two windows side-by-side would probably want to set a "default" for creating new windows.

I may not understand the logic fully of saving the last window size, but let's say I normally have my windows at 900x450 and then open a new window and resize it to fit in the bottom right corner of my screen for a quick command, or maybe a plugin is creating a new window for me, then that window would overwrite the last size and my next new window would be messed up and i'd have to resize it back to my preferred default. If I have defaults, I don't have to worry about resizing windows messing with my preferences.

So, thinking through the logic for window creation dimensions:

`windowSize` -> `last window size` -> fallback

So, I would actually remove `windowSize` from the default config, and have that be an optional config that users can set if they prefer to always create new windows with their preferred size.

**Comment by rauchg** [comment]
Makes a lot of sense… Since it's a bit of advanced flag, maybe we should take it out of the default file? And we can document it here: https://github.com/zeit/hyperterm-website

**Comment by tamagokun** [comment]
Yep, exactly. Removing it from the default config should make it work nicely with memorizing window size and cover a lot of user preferences.

**Comment by tamagokun** [comment]
Done! PR over on https://github.com/zeit/hyperterm-website created as well.

**Comment by rauchg** [comment]
Sorry, one last rebase 🙏

**Comment by tamagokun** [comment]
all set 🎊

**Pull request merged**
