### PR TITLE
make update feed not only OS X

### PR DESCRIPTION
**Pull request by Haroenv**
I'm not sure what the url for others is, since I'm not fully sure if it already exists for other platforms.

### CODE REVIEW

**Comment by rauchg** [comment]
We should probably pass it dynamically. We are using: https://github.com/GitbookIO/nuts. You can probably look there for what the parameter names would be.

**Comment by rauchg** [comment]
Needs rebase

**Comment by Haroenv** [comment]
for Windows, it's `/win32`, quickly looking for what it is for linux

**Comment by rauchg** [comment]
@Haroenv can you rebase please?

**Comment by Haroenv** [comment]
Sure! forgot about this

**Comment by Haroenv** [comment]
I'm pretty sure that this PR doesn't add anything new that isn't already in that file. Closing now.

**Pull request closed without merging**
