### PR TITLE
Initial support for pressing ~ ^ " ' ` on international keyboard layouts until composed characters lands

### PR DESCRIPTION
**Pull request by MrRio**
When using an international keyboard mode, certain keys get sent over as 'Dead' keys, as they're meant to be used as modifiers.

This adds a fix which just takes the code, and triggers an insertion for the correct key. See issue here: https://github.com/zeit/hyperterm/issues/518

Ideally we'd want the full composed character support, but until that's working 100% this will get international users up and running.

### CODE REVIEW

**Comment by MrRio** [comment]
Steps to reproduce: 

1. On a Mac, add U.S. International - PC as a keyboard layout
2. Switch to it
3. Type the chars ~ ` ' " ^

**Comment by fecabianchi** [comment]
@MrRio i made a PR on your fix for Backquote (` ~)

**Comment by MrRio** [comment]
@fecabianchi Oh sweet – you got a link?

**Comment by fecabianchi** [comment]
@MrRio https://github.com/MrRio/hyperterm/pull/1/commits/88a0f54a00fe9e032dca967b27249f15efdf6779

**Comment by MrRio** [comment]
@fecabianchi What platform and keyboard layout are you on?

**Comment by MrRio** [comment]
It shows as IntlBackslash for me, so I've added both in order to cover both keyboard mappings

**Comment by MrRio** [comment]
Build broken due to https://github.com/zeit/hyperterm/pull/533

**Comment by iamstarkov** [comment]
does it fix #466 ?

**Comment by MrRio** [comment]
@iamstarkov It does yeah, can you try the latest master

**Pull request merged**
