### PR TITLE
issue-656/config-values-arent-scoped

### PR DESCRIPTION
**Pull request by BrianDGLS**
Pull request for [#656](https://github.com/zeit/hyperterm/issues/656)

## Changes

- `plugin.js` changed `cache.set('plugins', ...)` to `cache.set('hyperterm.plugins, ...)'`

### CODE REVIEW

**Comment by leo** [comment]
Cool! But please fix [these](https://github.com/zeit/hyperterm/search?utf8=✓&q=plugin-versions&type=Code) as well. 😊

**Comment by BrianDGLS** [comment]
@leo Thanks, updated.

**Comment by leo** [comment]
Please also sync the branch with master, so that it's up-to-date :blush:

**Comment by BrianDGLS** [comment]
Thanks @leo, it's now up to date with master.

**Comment by leo** [comment]
Thanks! ❤️

**Pull request merged**
