### PR TITLE
Document platform specific build dependencies in README.md

### PR DESCRIPTION
**Pull request by flybayer**
These are all taken from:
https://github.com/electron-userland/electron-builder/wiki/Multi-Platform-Build

### CODE REVIEW

**Comment by rauchg** [comment]
LGTM. Needs rebase.

**Comment by flybayer** [comment]
Rebased :white_check_mark:

**Comment by matheuss** [comment]
I think you'll need to rebase it again since I merged #662 😹

**Comment by flybayer** [comment]
Rebased :white_check_mark: :white_check_mark: :smile:

**Comment by matheuss** [comment]
Thank you! ☺️

**Pull request merged**
