### PR TITLE
Add support for multiple cursor shapes

### PR DESCRIPTION
**Pull request by rpunkfu**
Hi!

Just a little PR to add support for multiple cursor shapes used by hterm, let me know what do you think :)

demo

### CODE REVIEW

**Comment by rauchg** [comment]
woah that's so beautiful. Care documenting these in `hyperterm-website` repo?

**Comment by rauchg** [comment]
Also, we need to add it to `config-default` since I suspect some people would love to customize it (specifically, I *love* the looks of `BEAM`)

**Comment by rpunkfu** [comment]
Sure, will do! Beam is my favorite too! :)

**Comment by rpunkfu** [comment]
Which one should be default, block?

**Comment by rauchg** [comment]
`// `BEAM` for | shape, `UNDERLINE` for _, `BLOCK` for █

**Comment by rpunkfu** [comment]
I mean, which one should be set by default in `config-default.js`? :)

**Comment by rpunkfu** [comment]
I added `BLOCK` by default ;)

**Comment by rauchg** [comment]
image

**Pull request merged**
