### PR TITLE
Add support for opening the terminal on the correct display

### PR DESCRIPTION
**Pull request by MrRio**
See this issue https://github.com/zeit/hyperterm/issues/481

Opening a new window will now open it ever so slightly diagonally across from the current active window. This is the same behaviour as Terminal.app. I've got for the height of the header as the value.

screen shot 2016-07-30 at 17 46 20

### CODE REVIEW

**Comment by rauchg** [comment]
This is brilliant 👏. What happens if you go off-screen? Should we reset the `y` back to the starting point and shift the `x`?

**Comment by rauchg** [comment]
@MrRio I apologize for the poor braille character width calculation so far :P

**Comment by MrRio** [comment]
@rauchg hah, it's hardly the feature at the top of every terminal emulator's list. I'm pretty sure we can fix it by kicking the renderer into the same mode that creates <span>s for colored chars and some CSS.

Yeah the X and Y should reset, I'll knock that up

**Comment by MrRio** [comment]
This works well for me, let me know :)

**Comment by MrRio** [comment]
Build broken due to https://github.com/zeit/hyperterm/pull/533

**Pull request merged**
