### PR TITLE
babel-plugin-transform-es2015-modules-commonjs is not in devDependencies

### PR DESCRIPTION
**Pull request by stephenkingsley**
when I run `npm run dev`, `babel-plugin-transform-es2015-modules-commonjs` has not find. so update devDependencies in package.json file.

### CODE REVIEW

**Comment by rauchg** [comment]
actually this shouldn't be needed?

**Comment by rauchg** [comment]
The reason is that the bundle we use should already include everything you need. Try running `npm install` again? And perhaps `npm cache clean`?

**Comment by stephenkingsley** [comment]
> The reason is that the bundle we use should already include everything you need. Try running npm install again? And perhaps npm cache clean?

I git clone, and then `npm i`. when I run dev, it warning me can not find `babel-plugin-transform-es2015-modules-commonjs`. maybe is the npm's problem.

**Comment by albinekb** [comment]
```
git status && node --version && npm --version && npm ls
```

**Comment by stephenkingsley** [comment]
@albinekb what is the problem? can you tell me?

**Pull request merged**
